when:
  - event: push
    branch: main
  - event: push
    branch: custom
  - event: manual

steps:
  build-golang:
    image: golang:1.22
    commands:
      - go build -ldflags="-s -w" -o hawser ./cmd/hawser

  build-latest:
    image: woodpeckerci/plugin-docker-buildx
    when:
      - event: push
        branch: main
      - event: manual
    settings:
      repo: registry.kcolb.com/ludx/hawser
      registry: registry.kcolb.com
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: latest
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - build-golang

  build-custom:
    image: woodpeckerci/plugin-docker-buildx
    when:
      - event: push
        branch: custom
      - event: manual
    settings:
      repo: registry.kcolb.com/ludx/hawser
      registry: registry.kcolb.com
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      tags: custom
      platforms:
        - linux/amd64
        - linux/arm64
    depends_on:
      - build-golang
